MATERIAL_MAP_DIFFUSE = MATERIAL_MAP_ALBEDO;
MATERIAL_MAP_SPECULAR = MATERIAL_MAP_METALNESS;

SHADER_LOC_MAP_DIFFUSE = SHADER_LOC_MAP_ALBEDO;
SHADER_LOC_MAP_SPECULAR = SHADER_LOC_MAP_METALNESS;

LIGHTGRAY: TColor  = (r: 200; g: 200; b: 200; a: 255);
GRAY: TColor       = (r: 130; g: 130; b: 130; a: 255);
DARKGRAY: TColor   = (r: 80; g: 80; b: 80; a: 255);
YELLOW: TColor     = (r: 253; g: 249; b: 0; a: 255);
GOLD: TColor       = (r: 255; g: 203; b: 0; a: 255);
ORANGE: TColor     = (r: 255; g: 161; b: 0; a: 255);
PINK: TColor       = (r: 255; g: 109; b: 194; a: 255);
RED: TColor        = (r: 230; g: 41; b: 55; a: 255);
MAROON: TColor     = (r: 190; g: 33; b: 55; a: 255);
GREEN: TColor      = (r: 0; g: 228; b: 48; a: 255);
LIME: TColor       = (r: 0; g: 158; b: 47; a: 255);
DARKGREEN: TColor  = (r: 0; g: 117; b: 44; a: 255);
SKYBLUE: TColor    = (r: 102; g: 191; b: 255; a: 255);
BLUE: TColor       = (r: 0; g: 121; b: 241; a: 255);
DARKBLUE: TColor   = (r: 0; g: 82; b: 172; a: 255);
PURPLE: TColor     = (r: 200; g: 122; b: 255; a: 255);
VIOLET: TColor     = (r: 135; g: 60; b: 190; a: 255);
DARKPURPLE: TColor = (r: 112; g: 31; b: 126; a: 255);
BEIGE: TColor      = (r: 211; g: 176; b: 131; a: 255);
BROWN: TColor      = (r: 127; g: 106; b: 79; a: 255);
DARKBROWN: TColor  = (r: 76; g: 63; b: 47; a: 255);

WHITE: TColor     = (r: 255; g: 255; b: 255; a: 255);
BLACK: TColor     = (r: 0; g: 0; b: 0; a: 255);
BLANK: TColor     = (r: 0; g: 0; b: 0; a: 0);
MAGENTA: TColor   = (r: 255; g: 0; b: 255; a: 255);
RAYWHITE: TColor  = (r: 245; g: 245; b: 245; a: 255);